"""Add image_file to Message model

Revision ID: 20bb9adce7b0
Revises: 426e5c70070c
Create Date: 2024-08-26 02:17:13.968497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bb9adce7b0'
down_revision = '426e5c70070c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=120), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
